#!/usr/bin/python
import sys
import pyKairosDB

if(len(sys.argv) < 3):
    print("USAGE: python kube-learn <ip> <port>")
    exit(1)

ip   = sys.argv[1]
port = sys.argv[2]

c = pyKairosDB.connect(ip, port, False)

l = pyKairosDB.metadata.get_all_metric_names(c)

for e in l:
    print e

