#!/usr/bin/python

import sys, getopt
import pyKairosDB

def usage():
    print("usage: python kube-learn -i <ip> -p <port>")

if(len(sys.argv) < 3):
    usage()
    sys.exit(1)
try:
    opts, args = getopt.getopt(sys.argv[1:], 'i:p:')
except getopt.GetoptError as err:
    print(err)
    usage()
    sys.exit(1)

ip = ""
port = ""
for o, a in opts:
    if o == '-i':
        ip = a
    elif o == '-p':
        port = a

c = pyKairosDB.connect(ip, port, False)

l = pyKairosDB.metadata.get_all_metric_names(c)

for e in l:
    print e
